// Dummy data for development when backend is not connected
export const dummyJobs = [
  {
    id: '1',
    title: 'Frontend Developer Intern',
    company: 'TechStart Inc.',
    description: 'Looking for a passionate frontend developer to join our team. Experience with React is a plus.',
    location: 'Remote',
    type: 'Part-time',
    salary: '$20-30/hour',
    requiredSkills: ['React', 'JavaScript', 'HTML', 'CSS'],
    experienceLevel: 'Intermediate',
    tags: ['web-development', 'react', 'frontend'],
    timeCommitment: 'Part-time',
    createdAt: '2024-01-15',
    views: 150,
    applications: 12,
    status: 'open',
    postedBy: 'user1',
  },
  {
    id: '2',
    title: 'Backend Developer for Startup',
    company: 'StartupXYZ',
    description: 'Join an exciting startup building the next big thing. Node.js and MongoDB experience required.',
    location: 'Hybrid',
    type: 'Part-time',
    salary: '$25-35/hour',
    requiredSkills: ['Node.js', 'MongoDB', 'Express', 'REST API'],
    experienceLevel: 'Advanced',
    tags: ['backend', 'nodejs', 'startup'],
    timeCommitment: 'Part-time',
    createdAt: '2024-01-14',
    views: 200,
    applications: 18,
    status: 'open',
    postedBy: 'user2',
  },
  {
    id: '3',
    title: 'UI/UX Designer',
    company: 'Design Studio',
    description: 'Creative UI/UX designer needed for mobile app design projects.',
    location: 'Remote',
    type: 'Project-based',
    salary: '$30-40/hour',
    requiredSkills: ['Figma', 'Adobe XD', 'UI Design', 'UX Research'],
    experienceLevel: 'Intermediate',
    tags: ['design', 'ui-ux', 'mobile'],
    timeCommitment: 'Flexible',
    createdAt: '2024-01-13',
    views: 180,
    applications: 15,
    status: 'open',
    postedBy: 'user3',
  },
];

export const dummyUserProfile = {
  id: 'user1',
  name: 'John Doe',
  email: 'john@example.com',
  skills: ['React', 'JavaScript', 'Node.js', 'MongoDB'],
  experienceLevel: 'Intermediate',
  interests: ['web-development', 'startup', 'backend'],
  location: 'Remote',
  availability: 'Part-time',
};

